In [2]:
import numpy as np
import pandas as pd

In [4]:
df=pd.read_csv('breast_cancer.csv')

In [5]:
df

Sample code number  Clump Thickness  Uniformity of Cell Size  \
0               1000025                5                        1   
1               1002945                5                        4   
2               1015425                3                        1   
3               1016277                6                        8   
4               1017023                4                        1   
..                  ...              ...                      ...   
678              776715                3                        1   
679              841769                2                        1   
680              888820                5                       10   
681              897471                4                        8   
682              897471                4                        8   

     Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                           1                  1                            2   
1                           4                  5                            7   
2                           1                  1                            2   
3                           8                  1                            3   
4                           1                  3                            2   
..                        ...                ...                          ...   
678                         1                  1                            3   
679                         1                  1                            2   
680                        10                  3                            7   
681                         6                  4                            3   
682                         8                  5                            4   

     Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0              1                3                1        1      2  
1             10                3                2        1      2  
2              2                3                1        1      2  
3              4                3                7        1      2  
4              1                3                1        1      2  
..           ...              ...              ...      ...    ...  
678            2                1                1        1      2  
679            1                1                1        1      2  
680            3                8               10        2      4  
681            4               10                6        1      4  
682            5               10                4        1      4  

[683 rows x 11 columns]

In [6]:
df.isnull()


Sample code number  Clump Thickness  Uniformity of Cell Size  \
0                 False            False                    False   
1                 False            False                    False   
2                 False            False                    False   
3                 False            False                    False   
4                 False            False                    False   
..                  ...              ...                      ...   
678               False            False                    False   
679               False            False                    False   
680               False            False                    False   
681               False            False                    False   
682               False            False                    False   

     Uniformity of Cell Shape  Marginal Adhesion  Single Epithelial Cell Size  \
0                       False              False                        False   
1                       False              False                        False   
2                       False              False                        False   
3                       False              False                        False   
4                       False              False                        False   
..                        ...                ...                          ...   
678                     False              False                        False   
679                     False              False                        False   
680                     False              False                        False   
681                     False              False                        False   
682                     False              False                        False   

     Bare Nuclei  Bland Chromatin  Normal Nucleoli  Mitoses  Class  
0          False            False            False    False  False  
1          False            False            False    False  False  
2          False            False            False    False  False  
3          False            False            False    False  False  
4          False            False            False    False  False  
..           ...              ...              ...      ...    ...  
678        False            False            False    False  False  
679        False            False            False    False  False  
680        False            False            False    False  False  
681        False            False            False    False  False  
682        False            False            False    False  False  

[683 rows x 11 columns]

In [11]:

X=df.iloc[:,1:-1].values
y=df.iloc[:,-1].values

In [12]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=0)

In [14]:
from sklearn.linear_model import LogisticRegression
classifier=LogisticRegression(random_state=0)
classifier.fit(X_train,y_train)

LogisticRegression(random_state=0)

In [15]:
ypred=classifier.predict(X_test)

In [16]:
ypred

array([2, 2, 4, 4, 2, 2, 2, 4, 2, 2, 4, 2, 4, 2, 2, 2, 4, 4, 4, 2, 2, 2,
       4, 2, 4, 4, 2, 2, 2, 4, 2, 4, 4, 2, 2, 2, 4, 4, 2, 4, 2, 2, 2, 2,
       2, 2, 2, 4, 2, 2, 4, 2, 4, 2, 2, 2, 4, 4, 2, 4, 2, 2, 2, 2, 2, 2,
       2, 2, 4, 4, 2, 2, 2, 2, 2, 2, 4, 2, 2, 2, 4, 2, 4, 2, 2, 4, 2, 4,
       4, 2, 4, 2, 4, 4, 2, 4, 4, 4, 4, 2, 2, 2, 4, 4, 2, 2, 4, 2, 2, 2,
       4, 2, 2, 4, 2, 2, 2, 2, 2, 2, 2, 4, 2, 2, 4, 4, 2, 4, 2, 4, 2, 2,
       4, 2, 2, 4, 2])

In [18]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,ypred)
cm

array([[84,  3],
       [ 3, 47]])

In [25]:
from sklearn.model_selection import cross_val_score
accuracies=cross_val_score(estimator=classifier,X=X_train,y=y_train,cv=20)
accuracies

array([0.92857143, 0.96428571, 0.92857143, 1.        , 0.96428571,
       0.96428571, 1.        , 0.96296296, 0.96296296, 0.96296296,
       1.        , 1.        , 1.        , 0.96296296, 1.        ,
       0.92592593, 1.        , 0.96296296, 0.92592593, 0.96296296])

In [27]:
print("accuracies: {0:.2f} %".format(accuracies.mean()*100))
print("standard deviation: {0:.2f} %".format(accuracies.std()*100))

accuracies: 96.90 %
standard deviation: 2.64 %
